--- #YAML:1.0
name:                IO-Compress-Lzf
version:             2.010
abstract:            Write lzf files/buffers
license:             perl
author:              
    - Paul Marquess <pmqs@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Compress::LZF:                 0
    IO::Compress::Base:            2.010
    IO::Uncompress::Base:          2.010
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
